version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jairakdemo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jairakdemo
      MYSQL_USER: jairakuser
      MYSQL_PASSWORD: jairakpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jairakdemo-network

  api:
    build: .
    container_name: jairakdemo-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://jairakuser:jairakpassword@mysql:3306/jairakdemo"
      NODE_ENV: "production"
    depends_on:
      - mysql
    networks:
      - jairakdemo-network
    volumes:
      - ./uploads:/app/uploads

volumes:
  mysql_data:

networks:
  jairakdemo-network:
    driver: bridge
